# Basic Numpy 

In [115]:
import numpy as np

- array

- arange

In [116]:
# 1D
print np.array(range(5))
print np.arange(0,5)

print np.array(range(0,5,2))
print np.arange(0,5,2)

# 2D
print np.array([range(5),range(0,10,2)])

[0 1 2 3 4]
[0 1 2 3 4]
[0 2 4]
[0 2 4]
[[0 1 2 3 4]
 [0 2 4 6 8]]


- zeros

- ones

In [117]:
print np.zeros((2,5))
print np.ones((2,5))

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


-  identity matrix

In [118]:
print np.eye(3,3)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


- linspace

> return a third argument as length of return array which increase evenly from start to end

In [119]:
np.linspace(0,4,5)

array([ 0.,  1.,  2.,  3.,  4.])

- random

> rand() : uniform [0,1]

> randn(): standard normal 

> randint(): random integer between range ( included lower but excluded upper )

In [120]:
print np.random.rand(1,5)
print np.random.rand(5)
print np.random.randn(1,5)
print np.random.randint(1,5,(1,5))

[[ 0.23898811  0.06928877  0.99609682  0.60393981  0.55740805]]
[ 0.35953917  0.08828985  0.85700353  0.36493577  0.00209297]
[[ 0.00137528 -1.25471574  0.47570737  0.06465191  0.48517226]]
[[4 4 4 3 1]]


- reshape

> reshape the input array into new matrix

In [121]:
arr = np.random.randint(1,5,(2,3))
print arr
print arr.reshape(6)

[[2 3 3]
 [3 2 1]]
[2 3 3 3 2 1]


- max/min

- argmax/argmin ( return the index )

In [122]:
print arr.max(), arr.min()
print arr.argmax(), arr.argmin()

3 1
1 5


- shape

In [123]:
print arr.shape
arr = arr.reshape(6)
print arr.shape

(2, 3)
(6,)


- dtype

In [124]:
print arr.dtype

int64


- reference

In [125]:
# wrong
arr = np.arange(0,6)
test = arr[:2]
test[:] = 99
print arr

# correct
test = arr[:2].copy()
test[:] = 0
print arr

[99 99  2  3  4  5]
[99 99  2  3  4  5]


## index 

In [126]:
arr = np.arange(0,6)
arr = arr.reshape(2,3)
print arr
print arr[-1]
print arr[1][1]

[[0 1 2]
 [3 4 5]]
[3 4 5]
4


- ##### index2 single brackets

In [127]:
print arr[1][1]
print arr[1,1]
print arr[:,1:] # can also get sub matrix
print arr[:][1:] # different from above

4
4
[[1 2]
 [4 5]]
[[3 4 5]]


- bool / filter

> conditional selection

In [128]:
print arr[arr < 10]

[0 1 2 3 4 5]


## Operation

> +, -, *, / : take operation on same position element

- Notice that if devide by 0, you will get nan or inf

In [129]:
print np.arange(5)/0.0

[ nan  inf  inf  inf  inf]


/anaconda/envs/OSMNX/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.
/anaconda/envs/OSMNX/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in divide
  """Entry point for launching an IPython kernel.


- np.square()

- np.exp()

- np.log()

- max() / min()

- argmax() / argmin()

$\hspace{1cm} \vdots$

- std()

- sum()

In [132]:
print arr.std()

print arr.sum(), np.sum(arr)

1.70782512766
15 15
